# SITE CONFIGURATION
baseurl: "/podcats"
title: "Plato AI Streams"
description: "Podcasters"
podcast-description: "Multiple verticle markets"
url:  "https://ilanh.github.io" # Actual base url of the website
author:
  name: "Ilan Harel"
  email: "@gmail.com"
  url: "https://"
# permalink: pretty
# permalink: /:title

keywords: [podcast, jekyll]

# THEME-SPECIFIC CONFIGURATION
avatar: assets/img/triangle.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Plato AI Streams # Change Blog header text
header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: Our sites at: https://platoblockchain.net/
# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]


#theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
